#!/usr/bin/perl
use strict;
use warnings;
#my @L = glob "JC2???_???_C58-met/coverage.gff";
my @L = glob "JC2???_???_fused-met/coverage.gff";
my %C;
my %M;
my @S;
local *FD;
foreach my $file (@L) {
  my $sample = substr $file, 0, 10;
  push @S, $sample;
  open FD, $file or die "Can't open $file : $!";
  while ( <FD> ) {
    next if /^#/;
    my @F = split /\t/;
    my ($chr) = $F[0] =~ /^[^|]+\|([^|]+)/;
    ($chr) = $F[0] =~ /^([^|\s]+)/ unless defined $chr;
    die "grmp $F[0]" unless defined $chr;
    $C{$chr} = {} unless defined $C{$chr};
    $C{$chr}->{$F[3]} = {} unless defined $C{$chr}->{$F[3]};
    my ($cov) = $F[8] =~ /cov=(\d+)/;
    $C{$chr}->{$F[3]}->{$sample} = $cov;
    $M{$chr} = $F[4] unless defined $M{$chr};
    $M{$chr} = $F[4] if $F[4] > $M{$chr};
  }
  close FD;
}
@S = sort @S;
print "chr\tstart\tend\t", join("\t",@S), "\n";
for my $chr (sort keys %C) {
  my $pos = 1;
  while ($pos < $M{$chr}) {
    #my $end = $pos + 1999;
    my $end = $pos + 4999;
    $end = $M{$chr} if $pos > $M{$chr};
    print "$chr\t$pos\t$end";
    for my $sample (@S) {
      my $val = $C{$chr}->{$pos}->{$sample};
      $val = 0 unless defined $val;
      print "\t$val";
    }
    print "\n";
    $pos = $end + 1;
  }
}
exit 0;
__END__
==> JC2140_neg_C58-met/coverage.gff <==
##gff-version 3
##date 2021-09-25T01:59:34
##source PACBIO_AlignmentSummary 1.0
##source-commandline summarize_coverage.py --log-level INFO /data/data1/chris/jobs_root.default/cromwell-executions/pb_basemods/92c507b8-5ada-4641-906a-ccbde3c7cec4/call-coverage_reports/coverage_reports/e0456ba4-339c-4363-9d98-313946590f8e/call-summarize_coverage/inputs/90199169/mapped.alignmentset.xml /data/data1/chris/jobs_root.default/cromwell-executions/pb_basemods/92c507b8-5ada-4641-906a-ccbde3c7cec4/call-coverage_reports/coverage_reports/e0456ba4-339c-4363-9d98-313946590f8e/call-summarize_coverage/inputs/-1952847430/smrtlink_reference.referenceset.xml coverage.gff
##sequence-header chr|NC_003062| chr|NC_003062|
##sequence-header chr|NC_003063| chr|NC_003063|
##sequence-header rs|NC_003064| rs|NC_003064|
##sequence-header rs|NC_003065| rs|NC_003065|
##sequence-region chr|NC_003062| 1 2841580
##sequence-region chr|NC_003063| 1 2075577
##sequence-region rs|NC_003064| 1 542868
##sequence-region rs|NC_003065| 1 214233
chr|NC_003062|	.	region	1	2000	0.00	+	.	cov=1391,2594,2667;cov2=2592.763,60.830;gaps=0,0
chr|NC_003062|	.	region	2001	4000	0.00	+	.	cov=2581,2614,2650;cov2=2616.191,16.916;gaps=0,0

==> JC2307_neg_C58-met/coverage.gff <==
##gff-version 3
##date 2021-09-25T02:32:23
##source PACBIO_AlignmentSummary 1.0
##source-commandline summarize_coverage.py --log-level INFO /data/data1/chris/jobs_root.default/cromwell-executions/pb_basemods/94c18631-fb69-4a40-837f-b96a6bee39eb/call-coverage_reports/coverage_reports/d7b96e58-0b51-40fe-882b-9002aee2984e/call-summarize_coverage/inputs/2086532601/mapped.alignmentset.xml /data/data1/chris/jobs_root.default/cromwell-executions/pb_basemods/94c18631-fb69-4a40-837f-b96a6bee39eb/call-coverage_reports/coverage_reports/d7b96e58-0b51-40fe-882b-9002aee2984e/call-summarize_coverage/inputs/1207456413/smrtlink_reference.referenceset.xml coverage.gff
##sequence-header chr|NC_003062| chr|NC_003062|
##sequence-header chr|NC_003063| chr|NC_003063|
##sequence-header rs|NC_003064| rs|NC_003064|
##sequence-header rs|NC_003065| rs|NC_003065|
##sequence-region chr|NC_003062| 1 2841580
##sequence-region chr|NC_003063| 1 2075577
##sequence-region rs|NC_003064| 1 542868
##sequence-region rs|NC_003065| 1 214233
chr|NC_003062|	.	region	1	2000	0.00	+	.	cov=1461,2829,2869;cov2=2815.954,73.317;gaps=0,0
chr|NC_003062|	.	region	2001	4000	0.00	+	.	cov=2864,2946,3027;cov2=2934.635,41.062;gaps=0,0

==> JC2307_pos_C58-met/coverage.gff <==
##gff-version 3
##date 2021-09-25T02:27:44
##source PACBIO_AlignmentSummary 1.0
##source-commandline summarize_coverage.py --log-level INFO /data/data1/chris/jobs_root.default/cromwell-executions/pb_basemods/13b93e1c-55f6-4991-b1bd-3cde28f5a1ee/call-coverage_reports/coverage_reports/8761fbea-29fc-4caa-bd2e-9a6f958e7905/call-summarize_coverage/inputs/-1954921139/mapped.alignmentset.xml /data/data1/chris/jobs_root.default/cromwell-executions/pb_basemods/13b93e1c-55f6-4991-b1bd-3cde28f5a1ee/call-coverage_reports/coverage_reports/8761fbea-29fc-4caa-bd2e-9a6f958e7905/call-summarize_coverage/inputs/-759952842/smrtlink_reference.referenceset.xml coverage.gff
##sequence-header chr|NC_003062| chr|NC_003062|
##sequence-header chr|NC_003063| chr|NC_003063|
##sequence-header rs|NC_003064| rs|NC_003064|
##sequence-header rs|NC_003065| rs|NC_003065|
##sequence-region chr|NC_003062| 1 2841580
##sequence-region chr|NC_003063| 1 2075577
##sequence-region rs|NC_003064| 1 542868
##sequence-region rs|NC_003065| 1 214233
chr|NC_003062|	.	region	1	2000	0.00	+	.	cov=1286,2581,2628;cov2=2555.562,87.501;gaps=0,0
chr|NC_003062|	.	region	2001	4000	0.00	+	.	cov=2530,2627,2701;cov2=2625.385,48.733;gaps=0,0
